### PR TITLE
feat: add video scroll component

### PR DESCRIPTION
**Pull request by Shurtu-gal**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [x] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Comment by ratnakar5938** [comment]
@Shurtu-gal ig it is not working in the preview

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal ig it is not working in the preview

The window element is not supported by Gatsby.

Currently solving it

**Comment by Sonakshi1901** [comment]
@Shurtu-gal resolve all the conflicts in this branch. To fix the deployment errors, try pulling all the recent code and deploying again.

**Comment by Sonakshi1901** [comment]
> ### Your checklist for this pull request
> 🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
> 
> * [ ]  Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
> * [ ]  Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
> * [ ]  Check the commit's or even all commits' message styles matches our requested structure.
> * [ ]  Check your code additions will fail neither code linting checks nor unit test.
> * [ ]  I have added necessary documentation (if appropriate)
> 
> ### Description
> Please describe your pull request.
> 
> ❤️Thank you!
> 
> ### Post merge checklist
> * [ ]  Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
> * [ ]  If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

@Shurtu-gal make sure you tick all the boxes in the checklist section. Make it a habit everytime you send a PR

**Pull request closed without merging**
