### PR TITLE
fix: FAQ section scroll.

### PR DESCRIPTION
**Pull request by padmajabhol**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Review by DesignrKnight — APPROVED** [review]
Looks great now

**Comment by CIPHERTron** [comment]
Performance keeps on decreasing every time 😢 
@riteshsp2000 @abhibhaw do you think we should convert all the images to webp format? This would surely give us a huge performance boost.

Also, I don't understand why the main thread work is taking over 10s 🤔

**Comment by CIPHERTron** [comment]
Also, @padmajabhol one last change. I noticed just now that the sponsor logos don't have an `alt` property which was affecting our accessibility score. Could you please add the same?
You can find it here: https://github.com/dscnitrourkela/project-oregano/blob/main/config/content/Sponsors.js

**Comment by abhibhaw** [comment]
> Performance keeps on decreasing every time 😢
> @riteshsp2000 @abhibhaw do you think we should convert all the images to webp format? This would surely give us a huge performance boost.
> 
> Also, I don't understand why the main thread work is taking over 10s 🤔

Webp isn't supported at all devices :( if we can have webp for supported devices and png for rest than it would be great !!

**Comment by padmajabhol** [comment]
> Also, @padmajabhol one last change. I noticed just now that the sponsor logos don't have an `alt` property which was affecting our accessibility score. Could you please add the same?
> You can find it here: https://github.com/dscnitrourkela/project-oregano/blob/main/config/content/Sponsors.js

sure.

**Review by CIPHERTron — APPROVED** [review]

**Comment by riteshsp2000** [comment]
> Performance keeps on decreasing every time 😢
> @riteshsp2000 @abhibhaw do you think we should convert all the images to webp format? This would surely give us a huge performance boost.
> 
> Also, I don't understand why the main thread work is taking over 10s 🤔

I think lets get the new updates and all other things up and finished. Once we have those things in motion, we'll try to get the performance up!

**Review by riteshsp2000 — APPROVED** [review]

**Pull request merged**
