### PR TITLE
feat: Add Contact Us Section

### PR DESCRIPTION
**Pull request by Sonakshi1901**
This PR adds a Contact Us form within FAQ Section.

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [X] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [X] Check the commit's or even all commits' message styles matches our requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit test.
- [X] I have added necessary documentation (if appropriate)

### Description
This PR adds Contact Us section

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Comment by riteshsp2000** [comment]
Hey @Sonakshi1901 A few changes before reviewing the code.

1. The font of the error of the form is not Roboto. Shift that to the robot. 
2. The errors are not updating after entering the proper email.
3. The button stylings are a bit off. Instead of making the entire button white, just make the border white colour with the text white. When hovered on the button, you can fill it with white colour and make the text black instead of the current black background on the shower.

**Comment by Sonakshi1901** [comment]
I'll look into this and make the necessary changes.

**Comment by riteshsp2000** [comment]
@Sonakshi1901 Looks good to me. Final changes
1. Pull the main branch and integrate with the FAQ section grid.
2. The font Family of error is not roboto. Update that as well. Otherwise its all good to go
3.

**Comment by Sonakshi1901** [comment]
There is one more change needed to be done to improve the responsiveness of the contact form

**Review by abhibhaw — CHANGES_REQUESTED** [review]
Check the "Have a ques" part grid on mobile layout, and @CIPHERTron again that CSS late loading issue here as well. The tracks section seems awesome 🚀

**Comment by abhibhaw** [comment]
> There is one more change needed to be done to improve the responsiveness of the contact form

oo Cool cool!

**Comment by CIPHERTron** [comment]
> Check the "Have a ques" part grid on mobile layout, and @CIPHERTron again that css late loading issue here as well. Tracks section seems awesome 🚀 

Ofc, the plugins haven't been added yet🥲
@riteshsp2000 will add the plugins and setup Gatsby config🚀

**Comment by Sonakshi1901** [comment]
> Check the "Have a ques" part grid on mobile layout, and @CIPHERTron again that CSS late loading issue here as well. The tracks section seems awesome 🚀

Ok

**Comment by Sonakshi1901** [comment]
@abhibhaw I have made all the necessary changes regarding mobile view. I have used media queries to make the responsiveness better. Do check and let me know if there are any more changes to be made.

**Review by abhibhaw — APPROVED** [review]

**Comment by abhibhaw** [comment]
Good work so far @Sonakshi1901 🎉

**Comment by CIPHERTron** [comment]
Thanks, @Sonakshi1901. Great job!
I'll handle it from here!

**Review by riteshsp2000 — APPROVED** [review]

**Comment by riteshsp2000** [comment]
@all-contributors add @Sonakshi1901  for Code

**Pull request merged**
